### ISSUE TITLE
Grey bar instead of camera image

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/hassio-addons#1]
I get this error:
```
2019-08-01 07:50:52 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
2019-08-01 08:28:20 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal error on transport TCPTransport (error status in uv_stream_t.read callback)
TimeoutError: [Errno 110] Operation timed out
```

and see the following

![image](https://user-images.githubusercontent.com/11855322/62323006-41021a00-b49e-11e9-928e-63590065f25a.png)

Possibly https://github.com/home-assistant/home-assistant/issues/12624

**Comment by robmarkcole** [comment]
Still an issue in Home Assistant 0.107.7

**Comment by robmarkcole** [comment]
appears fixed in ha 109
