### ISSUE TITLE
streamlit_basic won't start

### ISSUE THREAD

**Issue by davidusb-geek** [robmarkcole/hassio-addons#11]
The streamlit-basic add-on won't even start.

This is the error thrown:

```
Generate machine-id
Traceback (most recent call last):
  File "/usr/local/bin/streamlit", line 5, in <module>
    from streamlit.cli import main
  File "/usr/local/lib/python3.8/site-packages/streamlit/__init__.py", line 74, in <module>
    subprocess.run(["sudo", "dbus-uuidgen", "--ensure"])
  File "/usr/local/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo'
```

Here are my system specs:

```
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.4
Frontend 20230110.0 - latest
```

**Comment by robmarkcole** [comment]
I do recall that streamlit used to require `sudo`, probably that has changed now

**Comment by davidusb-geek** [comment]
Maybe we should try to update streamlit, they are already on version 1.17.0.
I'm trying to understand how streamlit could be used along with the ingress method for HA add-ons, what should be the correct configuration for this?

**Comment by robmarkcole** [comment]
Tbh it is not something I have a strong interest in looking into.
